# SPDX-FileCopyrightText: 2025 IS14 Edit
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# IS14 Edit - Новая роль: Старший инженер
- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  skills:
    - ShuttleControl
    - AdvancedBuilding
  requirements:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 216000 # 60 hrs
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer" # IS14 Edit
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  extendedAccess:
  - Atmospherics
  special:
  - !type:AddComponentSpecial
    components:
    - type: EngineeringStaff

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    id: IS_PdaSeniorEngineer # IS14 Edit
  storage:
    back: []

- type: chameleonOutfit
  id: SeniorEngineerChameleonOutfit
  job: SeniorEngineer
  equipment:
    head: ClothingHeadHatBeretEngineering
    mask: ClothingMaskBreath
    neck: ClothingNeckScarfStripedOrange
    outerClothing: ClothingOuterWinterEngi
    gloves: ClothingHandsGlovesColorYellow
    shoes: ClothingShoesBootsMag
