- type: playTimeTracker
  id: JobSeniorExpeditioner

- type: playTimeTracker
  id: JobChurchServant

- type: playTimeTracker
  id: JobCommandSecretary

- type: playTimeTracker
  id: JobInternalControlExecutor

- type: playTimeTracker
  id: JobSeniorEngineer

- type: playTimeTracker
  id: JobSeniorPhysician

- type: playTimeTracker
  id: JobSeniorResearcher

- type: playTimeTracker
  id: JobHosMilitia

- type: playTimeTracker
  id: JobMilitia

- type: playTimeTracker
  id: JobSeniorMilitia

- type: playTimeTracker
  id: IS_JobCadet

- type: playTimeTracker
  id: IS_JobPilot

- type: playTimeTracker
  id: JobInvestigator

- type: playTimeTracker
  id: JobMedOfficer

- type: playTimeTracker
  id: JobLrrChief

- type: playTimeTracker
  id: JobIvk

- type: playTimeTracker
  id: IS_JobLawyer

- type: playTimeTracker
  id: JobMupRepresentative
