#

- type: job
  id: ChurchServant
  name: job-name-church-servant
  description: job-description-church-servant
  playTimeTracker: JobChurchServant
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 9000 # 2.5 hours
  startingGear: ChurchServantGear
  icon: "JobIconChurchServant"
  supervisors: job-supervisors-hop
  access:
  - Chapel
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser # Lets them heal with bibles

- type: startingGear
  id: ChurchServantGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: IS_PdachaplainAssistant
    ears: ClothingHeadsetService
  storage:
    back:
    - ChaplainUndeterminedBible

- type: chameleonOutfit
  id: ChurchServantChameleonOutfit
  job: ChurchServant
  equipment:
    head: ClothingHeadHatPlaguedoctor
    eyes: ClothingEyesGlasses
    mask: ClothingMaskPlague
    neck: ClothingNeckStoleChaplain
    outerClothing: ClothingOuterPlagueSuit
    gloves: ClothingHandsGlovesColorBlack
