#

- type: job
  id: CommandSecretary
  name: job-name-command-secretary
  description: job-description-command-secretary
  playTimeTracker: JobCommandSecretary
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 9000 # 2.5 hours
  weight: 20
  startingGear: CommandSecretaryGear
  icon: "JobIconCommandSecretary"
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Command
  - HeadOfPersonnel
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CommandSecretaryGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: IS_PdaSecretary
    ears: ClothingHeadsetAltCommand
    belt: BoxFolderClipboard
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: CommandSecretaryChameleonOutfit
  job: CommandSecretary
  hasMindShield: true
  equipment:
    head: ClothingHeadHatHopcap
    eyes: ClothingEyesHudCommand
    mask: ClothingMaskNeckGaiterRed
    neck: ClothingNeckCloakHop
    outerClothing: ClothingOuterWinterHoP
